using System.Text.Json;

namespace AllyClicker.Core.Tests;

/// <summary>
/// Differential check against the Swift implementation.
/// </summary>
/// <remarks>
/// The fixture is generated by <c>macos/Sources/SettingsGolden</c> and records what the
/// reference decoder actually does with each document — not what anyone believes it does.
/// That distinction is the point: hand-ported assertions only ever cover what the original
/// author thought to assert, so they agree with a misreading as readily as with the truth.
///
/// Regenerate after any change to the Swift settings model (no Mac needed):
///   docker run --rm -v "$PWD/macos":/pkg -w /pkg swift:6.0 swift run SettingsGolden \
///     > windows/AllyClicker.Core.Tests/Fixtures/settings-golden.json
///
/// Comparison is structural rather than textual. Swift and C# both emit valid JSON but
/// differ in indentation and number formatting, and a string compare would fail on those
/// while telling us nothing about behaviour.
/// </remarks>
public class SettingsGoldenTests
{
    private static readonly IReadOnlyList<GoldenCase> Cases = LoadCases();

    public static TheoryData<string> CaseNames()
    {
        var data = new TheoryData<string>();
        foreach (var c in Cases) data.Add(c.Name);
        return data;
    }

    [Theory]
    [MemberData(nameof(CaseNames))]
    public void PortMatchesTheSwiftReference(string name)
    {
        var golden = Cases.Single(c => c.Name == name);

        var decoded = Settings.FromJson(golden.Input);
        using var actual = JsonDocument.Parse(decoded.ToJson());

        AssertJsonEquivalent(golden.Output, actual.RootElement, path: name);
    }

    [Fact]
    public void EffectiveDwell_MatchesTheSwiftReference()
    {
        // Derived from the calibration formula rather than read off the document, so no
        // amount of field-by-field comparison would catch a divergence here.
        foreach (var golden in Cases)
        {
            var decoded = Settings.FromJson(golden.Input);

            Assert.True(
                Math.Abs(decoded.EffectiveDwellMouseSeconds - golden.EffectiveDwellMouseSeconds) < 1e-9,
                $"{golden.Name}: effective dwell {decoded.EffectiveDwellMouseSeconds} " +
                $"!= reference {golden.EffectiveDwellMouseSeconds}");
        }
    }

    [Fact]
    public void FixtureIsNotSilentlyEmpty()
    {
        // A fixture that failed to generate would otherwise turn this whole file into a
        // green no-op, which is exactly the failure a golden suite must not have.
        Assert.True(Cases.Count >= 25, $"Only {Cases.Count} golden cases loaded.");
        Assert.Contains(Cases, c => c.Name == "defaults");
    }

    // MARK: - Structural comparison

    private static void AssertJsonEquivalent(JsonElement expected, JsonElement actual, string path)
    {
        Assert.True(expected.ValueKind == actual.ValueKind,
            $"{path}: kind {actual.ValueKind}, reference has {expected.ValueKind}");

        switch (expected.ValueKind)
        {
            case JsonValueKind.Object:
                var expectedProps = expected.EnumerateObject().ToDictionary(p => p.Name, p => p.Value);
                var actualProps = actual.EnumerateObject().ToDictionary(p => p.Name, p => p.Value);

                // Both directions: a key we drop and a key we invent are both divergence.
                Assert.True(
                    expectedProps.Keys.OrderBy(k => k).SequenceEqual(actualProps.Keys.OrderBy(k => k)),
                    $"{path}: keys [{string.Join(", ", actualProps.Keys.OrderBy(k => k))}], " +
                    $"reference has [{string.Join(", ", expectedProps.Keys.OrderBy(k => k))}]");

                foreach (var (key, expectedValue) in expectedProps)
                    AssertJsonEquivalent(expectedValue, actualProps[key], $"{path}.{key}");
                break;

            case JsonValueKind.Array:
                var expectedItems = expected.EnumerateArray().ToList();
                var actualItems = actual.EnumerateArray().ToList();
                Assert.True(expectedItems.Count == actualItems.Count,
                    $"{path}: {actualItems.Count} items, reference has {expectedItems.Count}");

                for (var i = 0; i < expectedItems.Count; i++)
                    AssertJsonEquivalent(expectedItems[i], actualItems[i], $"{path}[{i}]");
                break;

            case JsonValueKind.Number:
                // Swift writes 5 where C# may write 5.0; compare as numbers, not text.
                Assert.True(Math.Abs(expected.GetDouble() - actual.GetDouble()) < 1e-9,
                    $"{path}: {actual.GetDouble()}, reference has {expected.GetDouble()}");
                break;

            case JsonValueKind.String:
                Assert.Equal(expected.GetString(), actual.GetString());
                break;

            default:
                // true / false / null carry no payload beyond the kind already checked.
                break;
        }
    }

    // MARK: - Fixture loading

    private sealed record GoldenCase(
        string Name, string Input, JsonElement Output, double EffectiveDwellMouseSeconds);

    private static IReadOnlyList<GoldenCase> LoadCases()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "settings-golden.json");
        var document = JsonDocument.Parse(File.ReadAllText(path));

        return document.RootElement.EnumerateArray()
            .Select(c => new GoldenCase(
                c.GetProperty("name").GetString()!,
                c.GetProperty("input").GetRawText(),
                c.GetProperty("output").Clone(),
                c.GetProperty("effectiveDwellMouseSeconds").GetDouble()))
            .ToList();
    }
}
